apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: image_name
        ports:
        - containerPort: 8998
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 8998
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 5
        livenessProbe:
          failureThreshold: 7
          httpGet:
            path: /health
            port: 8998
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
      imagePullSecrets:
      - name: ${{ secrets.DOCKER_REGISTRY }}
