name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  IMAGE_TAG: ${{ github.sha }}
  NAMESPACE: testing
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      - name: Install kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          version: 'latest'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@main
        with:
          version: 'latest'
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ env.GCP_SA_KEY }}
      - name: Set active service account
        run: |
            gcloud components install gke-gcloud-auth-plugin
            echo "${{ env.GCP_SA_KEY }}" | base64 --decode > /tmp/key.json
            gcloud auth activate-service-account --key-file=/tmp/key.json
      - name: Set Image on Deployment
        run: |
            sed -i "s|\(image:.*\)|image: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}|" kubernetes/deployment.yaml
            kubectl apply -f kubernetes/deployment.yaml -n "${{ env.NAMESPACE }}" 
            kubectl apply -f kubernetes/service.yaml -n "${{ env.NAMESPACE }}" 
